Tahsin/sdb solr
appscode-cloud/ui-wizards pull request #473
Opened 2024-05-29 09:54 UTC by SayedTahsin

2024-05-31 12:31 UTC, nurRiyad requested changes

2024-05-31 12:31 UTC, nurRiyad commented on charts/kubedbcom-solr-editor-options/ui/functions.js
> +  setResourceLimit2,
fix linting

2024-05-31 12:31 UTC, nurRiyad commented on charts/kubedbcom-solr-editor-options/ui/functions.js
> +function setResourceLimit2({ commit, model, getValue, watchDependency },nodeType) {
rename funtion

2024-05-31 12:31 UTC, nurRiyad commented on charts/kubedbcom-solr-editor-options/ui/functions.js
> +      value: machines[modelPathValue].resources.limits.cpu,
use optional parameter

2024-05-31 12:31 UTC, nurRiyad commented on charts/kubedbcom-solr-editor-options/ui/functions.js
> +function disableLimit2({ model, getValue, watchDependency },nodeType) {
rename

2024-05-31 12:31 UTC, nurRiyad commented on charts/kubedbcom-singlestore-editor-options/ui/functions.js
>        value: machines[modelPathValue].resources.limits.cpu,
use optional chaining

2024-05-31 12:31 UTC, nurRiyad commented on charts/kubedbcom-singlestore-editor-options/ui/create-ui.yaml
> +
remove space

2024-06-03 10:42 UTC, SamiulSourav approved these changes
LGTM

2024-06-03 10:46 UTC, nurRiyad approved these changes
LGTM

2024-06-03 10:46 UTC, merged